name: 제안 리포트
description: 아이디어를 제안합니다.
title: ":asterisk: "
labels: [ "공통","기능" ]
assignees:
  - shirohoo
  - gunkim
  - Junnyjun
body:
  - type: markdown
    attributes:
      value: |
        아이디어를 제공해 주셔서 감사합니다.
  - type: input
    id: contact
    attributes:
      label: 연락처 세부 정보
      description: 추가 정보가 필요한 경우 어떻게 연락할 수 있나요?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 어떤 아이디어를 가지고 있나요?
      description: 아이디어를 상세하게 설명해 주실 수 있나요?
      placeholder: 알아보기 쉽게 작성해주세요
      value: "#### 💭 제목을 입력해 주세요  \n
      > 🐬 부제 1\n 
      \n
      해야할일 작성"
    validations:
      required: true
  - type: dropdown
    id: position
    attributes:
      label: 어떤 포지션에서 발생한 제안인가요?
      multiple: true
      options:
        - FRONTEND
        - BACKEND
        - INFRA
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: 기여자 행동 강령
      description: 이 문제를 제출하면 [기여자 행동 강령](https://github.com/telos-projects/fish-25/blob/main/docs/CODE_OF_CONDUCT.adoc)을 준수하는 데 동의하는 것으로 간주합니다.
      options:
        - label: 나는 이 프로젝트의 행동 강령을 따를 것에 동의합니다
          required: true