= 기여자 행동 강령

이 프로젝트의 기여자이자 유지자로서, 그리고 개방적인 커뮤니티를 위해 우리는 문제 보고, 기능 요청 게시, 문서 업데이트, 풀 요청 또는 패치 제출 및 기타 활동을 통해 기여하는 모든 사람들을 존중할 것을 약속드립니다.

우리는 이 프로젝트에 기여하는 모든 사람이 고통 없는 경험을 할 수 있도록 최선을 다 할 것이며, 이는 경험 수준, 성별, 성 정체성 및 표현, 성적 취향, 장애, 외모, 신체 크기, 인종, 민족, 연령, 종교 또는 국적에 관계없이 모든 사람에게 적용 될 것입니다.

모든 기여자가 용인할 수 없는 행동의 예시는 다음과 같습니다.

* 성적인 언어나 이미지의 사용
* 인신공격
* 비하적 댓글 조롱 또는 모욕
* 공개적이거나 사적인 괴롭힘
* 명시적인 허가 없이 물리적 또는 전자적으로 주소와 같은 타인의 개인 정보를 게시하는 행위
* 기타 비윤리적이거나 비전문적인 행위

프로젝트 관리자들은 이 행동 강령과 일치하지 않는 댓글, 커밋, 코드, 위키 편집, 문제 및 기타 기여를 제거, 편집 또는 거부하거나, 부적절하거나 위협적이거나 공격적이거나 유해한 것으로 간주합니다.

이 행동 강령을 채택함으로써 프로젝트 관리자들은 이러한 원칙을 이 프로젝트 관리의 모든 측면에 공정하고 일관되게 적용할 것을 약속드리며, 행동 강령을 따르지 않거나 시행하지 않는 프로젝트 관리자는 이 프로젝트 팀에서 영구적으로 퇴출 될 수 있습니다.

이 행동 강령은 개인이 프로젝트 또는 해당 커뮤니티를 대표할 때 프로젝트 공간과 공공 장소 모두에 적용됩니다.

욕설, 괴롭힘 또는 기타 용납할 수 없는 행동의 사례는 projects.telos@gmail.com 으로 고발할 수 있습니다.
모든 사항은 프로젝트 관리자들에 의해 검토 및 조사되며 상황에 따라 필요하고 적절하다고 판단되는 응답을 받게 될 것입니다.
또한, 모든 프로젝트 관리자는 고발자와 관련한 모든 정보에 대해 기밀을 유지해야 할 의무가 있습니다.

이 행동 강령은 https://contributor-covenant.org[컨트리뷰터 규약], 버전 1.3.0에서 수정되었으며, https://contributor-covenant.org/version/1/3/0/[contributor-covenant.org/version/1/3/0/] 에서 볼 수 있습니다